//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A17ProjetMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal site() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A17ProjetMVC.Resources.site", typeof(site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avaible Objects.
        /// </summary>
        public static string AvaibleObjects {
            get {
                return ResourceManager.GetString("AvaibleObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Borrow.
        /// </summary>
        public static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End date.
        /// </summary>
        public static string borrowEndDate {
            get {
                return ResourceManager.GetString("borrowEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is delivered.
        /// </summary>
        public static string borrowIsDelivered {
            get {
                return ResourceManager.GetString("borrowIsDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service rating.
        /// </summary>
        public static string borrowServiceRating {
            get {
                return ResourceManager.GetString("borrowServiceRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start date.
        /// </summary>
        public static string borrowStartDate {
            get {
                return ResourceManager.GetString("borrowStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of days.
        /// </summary>
        public static string borrowVMDayNumber {
            get {
                return ResourceManager.GetString("borrowVMDayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new.
        /// </summary>
        public static string buttonCreateNew {
            get {
                return ResourceManager.GetString("buttonCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string modelAccEmail {
            get {
                return ResourceManager.GetString("modelAccEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        public static string modelCategoryName {
            get {
                return ResourceManager.GetString("modelCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm the password.
        /// </summary>
        public static string modelConfirmPass {
            get {
                return ResourceManager.GetString("modelConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memorize the password ?.
        /// </summary>
        public static string modelMemorizePass {
            get {
                return ResourceManager.GetString("modelMemorizePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string modelPassword {
            get {
                return ResourceManager.GetString("modelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string modelUserAddress {
            get {
                return ResourceManager.GetString("modelUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Telephone Number.
        /// </summary>
        public static string modelUserTel {
            get {
                return ResourceManager.GetString("modelUserTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is available.
        /// </summary>
        public static string objectAvailable {
            get {
                return ResourceManager.GetString("objectAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string objectDescription {
            get {
                return ResourceManager.GetString("objectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object Name.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication Date.
        /// </summary>
        public static string objectPublicationDate {
            get {
                return ResourceManager.GetString("objectPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average Rating.
        /// </summary>
        public static string statAvgRating {
            get {
                return ResourceManager.GetString("statAvgRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string statFirstName {
            get {
                return ResourceManager.GetString("statFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        public static string statLastName {
            get {
                return ResourceManager.GetString("statLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration Number.
        /// </summary>
        public static string statRegistrationNumber {
            get {
                return ResourceManager.GetString("statRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string statTitle {
            get {
                return ResourceManager.GetString("statTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 members appreciated of the month.
        /// </summary>
        public static string statTop5AppreciatedMonth {
            get {
                return ResourceManager.GetString("statTop5AppreciatedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 members appreciated of the week.
        /// </summary>
        public static string statTop5AppreciatedWeek {
            get {
                return ResourceManager.GetString("statTop5AppreciatedWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 generous members of the month.
        /// </summary>
        public static string statTop5GenerousMonth {
            get {
                return ResourceManager.GetString("statTop5GenerousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 generous members of the week.
        /// </summary>
        public static string statTop5GenerousWeek {
            get {
                return ResourceManager.GetString("statTop5GenerousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 least sought after categories of the month.
        /// </summary>
        public static string statTop5LeastSoughtMonth {
            get {
                return ResourceManager.GetString("statTop5LeastSoughtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 least sought after categories of the week.
        /// </summary>
        public static string statTop5LeastSoughtWeek {
            get {
                return ResourceManager.GetString("statTop5LeastSoughtWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 most sought after categories of the month.
        /// </summary>
        public static string statTop5MostSoughtMonth {
            get {
                return ResourceManager.GetString("statTop5MostSoughtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 most sought after categories of the week.
        /// </summary>
        public static string statTop5MostSoughtWeek {
            get {
                return ResourceManager.GetString("statTop5MostSoughtWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count.
        /// </summary>
        public static string topCategorieCount {
            get {
                return ResourceManager.GetString("topCategorieCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of objects.
        /// </summary>
        public static string topMemberObjCount {
            get {
                return ResourceManager.GetString("topMemberObjCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Satisfaction..
        /// </summary>
        public static string viewBorrowEvalSatisfaction {
            get {
                return ResourceManager.GetString("viewBorrowEvalSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate your satisfaction for the product by giving it a score between 1 and 5.
        /// </summary>
        public static string viewBorrowEvalTextSatisfaction {
            get {
                return ResourceManager.GetString("viewBorrowEvalTextSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Borrow Evaluation.
        /// </summary>
        public static string viewBorrowEvalTitle {
            get {
                return ResourceManager.GetString("viewBorrowEvalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tell us about your experience.
        /// </summary>
        public static string viewBorrowRatingExperience {
            get {
                return ResourceManager.GetString("viewBorrowRatingExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation of your satisfaction.
        /// </summary>
        public static string viewBorrowRatingSatisfaction {
            get {
                return ResourceManager.GetString("viewBorrowRatingSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation of the borrow.
        /// </summary>
        public static string viewBorrowRatingTitle {
            get {
                return ResourceManager.GetString("viewBorrowRatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to list.
        /// </summary>
        public static string viewCreateBackToList {
            get {
                return ResourceManager.GetString("viewCreateBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object.
        /// </summary>
        public static string viewCreateObject {
            get {
                return ResourceManager.GetString("viewCreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string viewCreateTitle {
            get {
                return ResourceManager.GetString("viewCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this?.
        /// </summary>
        public static string viewDeleteConfirmDelete {
            get {
                return ResourceManager.GetString("viewDeleteConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string viewDeleteTitle {
            get {
                return ResourceManager.GetString("viewDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string viewEditTitle {
            get {
                return ResourceManager.GetString("viewEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return.
        /// </summary>
        public static string viewMyBorrowGiveBack {
            get {
                return ResourceManager.GetString("viewMyBorrowGiveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Belongs to.
        /// </summary>
        public static string viewMyObjectBelongTo {
            get {
                return ResourceManager.GetString("viewMyObjectBelongTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no object to show..
        /// </summary>
        public static string viewObjectIndexElseList {
            get {
                return ResourceManager.GetString("viewObjectIndexElseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the objects.
        /// </summary>
        public static string viewObjectIndexTitle {
            get {
                return ResourceManager.GetString("viewObjectIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available objects.
        /// </summary>
        public static string viewSharedAvailableObjects {
            get {
                return ResourceManager.GetString("viewSharedAvailableObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string viewSharedHome {
            get {
                return ResourceManager.GetString("viewSharedHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My borrows.
        /// </summary>
        public static string viewSharedMyBorrows {
            get {
                return ResourceManager.GetString("viewSharedMyBorrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My objects.
        /// </summary>
        public static string viewSharedMyObject {
            get {
                return ResourceManager.GetString("viewSharedMyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string viewSharedStat {
            get {
                return ResourceManager.GetString("viewSharedStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 5 Objects.
        /// </summary>
        public static string viewTop5ObjTitle {
            get {
                return ResourceManager.GetString("viewTop5ObjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top members.
        /// </summary>
        public static string viewTopMemberTitle {
            get {
                return ResourceManager.GetString("viewTopMemberTitle", resourceCulture);
            }
        }
    }
}
